version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    nakedret:
      max-func-lines: 30
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: errorf
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: var-declaration
        - name: unused-parameter
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - staticcheck
        path: tests/e2e/e2e_test.go
      - linters:
          - revive
        path: scripts/
      - linters:
          - revive
        text: stutters
      - linters:
          - revive
        text: package-comments
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
