version: 2

project_name: matrix

before:
  hooks:
    - go mod tidy

builds:
  - id: matrix
    main: ./cmd/matrix
    binary: matrix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: matrix
    ids:
      - matrix
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  disable: true
