run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - unused
    - unconvert
    - misspell
    - whitespace
    - nakedret
    - nilerr
    - revive
    - gocritic
    - errcheck

linters-settings:
  nakedret:
    max-func-lines: 30
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: errorf
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: var-declaration

issues:
  exclude-rules:
    - path: tests/e2e/e2e_test.go
      linters:
        - staticcheck
        - gocritic
